### ISSUE TITLE
Use Pygments to add syntax highlighting the code when using `cat`

### ISSUE THREAD

**Issue by BBloggsbott** [BBloggsbott/ghub#13]
Use [`pygments`](https://pygments.org) to add syntax highlighting. `TerminalFormatter` should work fine to print the output.

**Comment by BBloggsbott** [comment]
@mahanthathreyee An error is thrown when pygments cannot find the file type from the exception.

**Comment by mahanthathreyee** [comment]
Updated with a new PR #22, tested on my end, let me know if it works
