### ISSUE TITLE
Paginate the output of the cat command

### ISSUE THREAD

**Issue by BBloggsbott** [BBloggsbott/ghub#17]
Use [`pydoc`](https://docs.python.org/3.7/library/pydoc.html) to make the output of the `cat` command to pages to keep the terminal clean.

**Comment by mahanthathreyee** [comment]
pydoc is broken
looking for alternate
<img width="1680" alt="Screenshot 2020-03-07 at 2 35 47 PM" src="https://user-images.githubusercontent.com/26182655/76140488-f9b9b880-6080-11ea-9337-73238bb2d9c4.png">

**Comment by BBloggsbott** [comment]
Appears to work file for me. Check [this](https://stackoverflow.com/a/37585086/10715700) out.

**Comment by mahanthathreyee** [comment]
> Appears to work file for me. Check [this](https://stackoverflow.com/a/37585086/10715700) out.

PyDoc in itself isn't the issue, it's rendering of the colors
My bad should have mentioned in the previous comment, 
Created a new PR, that solves it by using shell [LESS](https://en.wikipedia.org/wiki/Less_(Unix))

**Comment by BBloggsbott** [comment]
OKay. Saw your PR
