### ISSUE TITLE
Add python function to interact with the following GitHub API endpoints.

### ISSUE THREAD

**Issue by BBloggsbott** [BBloggsbott/ghub#6]
* [x] main user
    * [x] authorize
    * [x] repos
    * [x] stars
    * [x] followers
    * [x] following
* [x] other users
    * [x] repos
    * [x] stars
    * [x] followers
    * [x] following

**Comment by vathzen** [comment]
Add Git Feed also? Maybe a RSS Feed implementation

**Comment by BBloggsbott** [comment]
Maybe in the later version. I want the base application completed for now.
